[leiningen] Import from preview branch
Master is currently unstable

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,41 +1,18 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-# Ensure this file is executable via chmod a+x lein, then place it
-# somewhere on your $PATH, like ~/bin. The rest of Leiningen will be
-# installed upon first run into the ~/.lein/self-installs directory.
-
-export LEIN_VERSION="2.0.0-SNAPSHOT"
+LEIN_VERSION="2.0.0-preview2"
+export LEIN_VERSION
 
 case $LEIN_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
     *) SNAPSHOT="NO" ;;
 esac
 
-if [[ "$OSTYPE" == "cygwin" ]]; then
-    delimiter=";"
-else
-    delimiter=":"
+# Make sure classpath is in unix format for manipulating, then put
+# it back to windows format when we use it
+if [ "$OSTYPE" = "cygwin" ] && [ "$CLASSPATH" != "" ]; then
+    CLASSPATH=`cygpath -up $CLASSPATH`
 fi
-
-function make_native_path {
-    # ensure we have native paths
-    if [[ "$OSTYPE" == "cygwin" && "$1"  == /* ]]; then
-	echo -n "$(cygpath -wp "$1")"
-    else
-	echo -n "$1"
-    fi
-}
-
-#  usage : add_path PATH_VAR [PATH]...
-function add_path {
-    local path_var=$1
-    shift
-    while [ -n "$1" ];do
-        # http://bashify.com/?Useful_Techniques:Indirect_Variables:Indirect_Assignment
-	export ${path_var}="${!path_var}${delimiter}$(make_native_path "$1")"
-	shift
-    done
-}
 
 if [ `id -u` -eq 0 ] && [ "$LEIN_ROOT" = "" ]; then
     echo "WARNING: You're currently running as root; probably by accident."
@@ -55,19 +32,21 @@ do
     fi
 done
 
-export LEIN_HOME=${LEIN_HOME:-"$HOME/.lein"}
-
-for f in "$LEIN_HOME/leinrc" ".leinrc"; do
-  if [ -e $f ]; then
-    source $f
+if [ "$LEIN_HOME" = "" ]; then
+  if [ -d "$PWD/.lein" ] && [ "$PWD" != "$HOME" ]; then
+    echo "Leiningen is running in bundled mode."
+    LEIN_HOME="$PWD/.lein"
+  else
+    LEIN_HOME="$HOME/.lein"
   fi
-done
-
-if [ "$OSTYPE" = "cygwin" ]; then
-    export LEIN_HOME=`cygpath -w $LEIN_HOME`
 fi
 
 LEIN_JAR="$LEIN_HOME/self-installs/leiningen-$LEIN_VERSION-standalone.jar"
+
+# apply context specific CLASSPATH entries
+if [ -f .lein-classpath ] && [ ! -f src/leiningen/version.clj ]; then
+    CLASSPATH="`cat .lein-classpath`:$CLASSPATH"
+fi
 
 # normalize $0 on certain BSDs
 if [ "$(dirname "$0")" = "." ]; then
@@ -88,10 +67,6 @@ while [ -h "$SCRIPT" ] ; do
 done
 
 BIN_DIR="$(dirname "$SCRIPT")"
-
-# Try to make the default more sane for :eval-in :classloader.lein
-grep -E -q '^\s*:eval-in\s+:classloader\s*$' project.clj 2> /dev/null &&
-LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-'-Xms64m -Xmx512m'}
 
 if [ -r "$BIN_DIR/../src/leiningen/version.clj" ]; then
     # Running from source checkout
@@ -120,27 +95,22 @@ if [ -r "$BIN_DIR/../src/leiningen/version.clj" ]; then
         ORIG_PWD="$PWD"
         cd "$LEIN_DIR"
 
-        $0 classpath .lein-classpath
-        sum $LEIN_DIR/project.clj $LEIN_DIR/leiningen-core/project.clj > \
-            .lein-project-checksum
+        # For some reason "$0" classpath > .lein-classpath doesn't work; wtf?
+        LEIN_CLASSPATH=$($0 classpath)
+        echo $LEIN_CLASSPATH > .lein-classpath
+        sum $LEIN_DIR/project.clj $LEIN_DIR/leiningen-core/project.clj > .lein-project-checksum
         cd "$ORIG_PWD"
     fi
 
     mkdir -p "$LEIN_DIR/target/classes"
-    export LEIN_JVM_OPTS="${LEIN_JVM_OPTS:--Xms64m -Xmx256m} -Dclojure.compile.path=$LEIN_DIR/target/classes"
-    add_path CLASSPATH "$LEIN_DIR/leiningen-core/src/" "$LEIN_DIR/leiningen-core/resources/" \
-                          "$LEIN_DIR/test:$LEIN_DIR/target/classes" "$LEIN_DIR/src" ":$LEIN_DIR/resources"
-
-    if [ -r "$LEIN_DIR/.lein-classpath" ]; then
-        add_path CLASSPATH "$(cat $LEIN_DIR/.lein-classpath 2> /dev/null)"
-    else
-        add_path CLASSPATH "$LEIN_DIR/leiningen-core/lib/*"
-    fi
-else # Not running from a checkout
-    add_path CLASSPATH "$LEIN_JAR"
-
-    # TODO: unify setting this; it's a complete mess. Should be able
-    # to easily modify jvm opts without losing bootclasspath
+    export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-"-Dclojure.compile.path=$LEIN_DIR/target/classes"}
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/leiningen-core/src/"
+    CLASSPATH="$CLASSPATH:$(cat $LEIN_DIR/.lein-classpath 2> /dev/null)"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/leiningen-core/lib/*"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/test:$LEIN_DIR/classes:$LEIN_DIR/src:$LEIN_DIR/resources:$LEIN_JAR"
+else
+    # Not running from a checkout
+    CLASSPATH="$CLASSPATH:$LEIN_JAR"
     export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-"-Xbootclasspath/a:$LEIN_JAR"}
 
     if [ ! -r "$LEIN_JAR" -a "$1" != "self-install" ]; then
@@ -148,34 +118,16 @@ else # Not running from a checkout
     fi
 fi
 
-if [ "$HTTP_CLIENT" = "" ]; then
-    if type -p curl >/dev/null 2>&1; then
-        if [ "$https_proxy" != "" ]; then
-            CURL_PROXY="-x $https_proxy"
-        fi
-        HTTP_CLIENT="curl $CURL_PROXY -f -L -o"
-    else
-        HTTP_CLIENT="wget -O"
+HTTP_CLIENT="wget --no-check-certificate -O"
+if type -p curl >/dev/null 2>&1; then
+    if [ "$https_proxy" != "" ]; then
+        CURL_PROXY="-x $https_proxy"
     fi
+    HTTP_CLIENT="curl $CURL_PROXY --insecure -f -L -o"
 fi
 
-function download_failed_message {
-    echo "Failed to download $1"
-    echo "It's possible your HTTP client's certificate store does not have the"
-    echo "correct certificate authority needed. This is often caused by an"
-    echo "out-of-date version of libssl. Either upgrade it or set HTTP_CLIENT"
-    echo "to turn off certificate checks:"
-    echo "  export HTTP_CLIENT=\"wget --no-check-certificate -O\" # or"
-    echo "  export HTTP_CLIENT=\"curl --insecure -f -L -o\""
-}
-
-# TODO: explain what to do when Java is missing
 export JAVA_CMD=${JAVA_CMD:-"java"}
 export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}
-
-if [[ "$(basename $LEIN_JAVA_CMD)" == *drip* ]]; then
-    export DRIP_INIT=$(printf -- "-e\n(require 'leiningen.repl)")
-fi
 
 # Support $JAVA_OPTS for backwards-compatibility.
 export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
@@ -189,19 +141,19 @@ if [ "$1" = "self-install" ]; then
       echo "If you wish to re-download, delete it and rerun \"$0 self-install\"."
       exit 1
     fi
-    echo "Downloading Leiningen to $LEIN_JAR now..."
-    mkdir -p $(dirname "$LEIN_JAR")
+    echo "Downloading Leiningen now..."
+    LEIN_DIR=`dirname "$LEIN_JAR"`
+    mkdir -p "$LEIN_DIR"
     LEIN_URL="https://github.com/downloads/technomancy/leiningen/leiningen-$LEIN_VERSION-standalone.jar"
-    $HTTP_CLIENT "$LEIN_JAR.pending" "$LEIN_URL"
-    if [ $? == 0 ]; then
-        # TODO: checksum
-        mv -f "$LEIN_JAR.pending" "$LEIN_JAR"
-    else
-        rm "$LEIN_JAR.pending" 2> /dev/null
-        download_failed_message "$LEIN_URL"
+    $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
+    if [ $? != 0 ]; then
+        echo "Failed to download $LEIN_URL"
         if [ $SNAPSHOT = "YES" ]; then
-            echo "See README.md for SNAPSHOT-specific build instructions."
+            echo "If you have Maven installed, you can do"
+            echo "mvn dependency:copy-dependencies; mv target/dependency lib"
+            echo "See README.md for further SNAPSHOT build instructions."
         fi
+        rm $LEIN_JAR 2> /dev/null
         exit 1
     fi
 elif [ "$1" = "upgrade" ]; then
@@ -218,8 +170,7 @@ elif [ "$1" = "upgrade" ]; then
         echo "You do not have permission to upgrade the installation in $SCRIPT"
         exit 1
     else
-        TARGET_VERSION="${2:-"preview"}"
-        echo "The script at $SCRIPT will be upgraded to the latest $TARGET_VERSION version."
+        echo "The script at $SCRIPT will be upgraded to the latest preview version."
         echo -n "Do you want to continue [Y/n]? "
         read RESP
         case "$RESP" in
@@ -227,20 +178,12 @@ elif [ "$1" = "upgrade" ]; then
                 echo
                 echo "Upgrading..."
                 TARGET="/tmp/lein-$$-upgrade"
-                if [ "$OSTYPE" = "cygwin" ]; then
-                    TARGET=`cygpath -w $TARGET`
-                fi
-                LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/$TARGET_VERSION/bin/lein"
-                $HTTP_CLIENT "$TARGET" "$LEIN_SCRIPT_URL"
-                if [ $? == 0 ]; then
-                    mv "$TARGET" "$SCRIPT" \
-                        && chmod +x "$SCRIPT" \
-                        && echo && "$SCRIPT" self-install \
-                        && echo && echo "Now running" `$SCRIPT version`
-                    exit $?
-                else
-                    download_failed_message "$LEIN_SCRIPT_URL"
-                fi;;
+                LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/preview/bin/lein"
+                $HTTP_CLIENT "$TARGET" "$LEIN_SCRIPT_URL" \
+                    && mv "$TARGET" "$SCRIPT" \
+                    && chmod +x "$SCRIPT" \
+                    && echo && "$SCRIPT" self-install && echo && echo "Now running" `$SCRIPT version`
+                exit $?;;
             *)
                 echo "Aborted."
                 exit 1;;
@@ -249,59 +192,35 @@ elif [ "$1" = "upgrade" ]; then
 else
     if [ "$OSTYPE" = "cygwin" ]; then
         # When running on Cygwin, use Windows-style paths for java
+        CLOJURE_JAR=`cygpath -w "$CLOJURE_JAR"`
         ORIGINAL_PWD=`cygpath -w "$ORIGINAL_PWD"`
-    fi
-
-    # apply context specific CLASSPATH entries
-    if [ -f .lein-classpath ]; then
-        add_path CLASSPATH "$(cat .lein-classpath)"
+        CLASSPATH=`cygpath -wp "$CLASSPATH"`
     fi
 
     if [ $DEBUG ]; then
-        echo "Leiningen's classpath: $CLASSPATH"
+        echo "Classpath: $CLASSPATH"
     fi
 
-    if ([ "$LEIN_FAST_TRAMPOLINE" != "" ] || [ -r .lein-fast-trampoline ]) &&
-        [ -r project.clj ]; then
-        INPUTS="$@ $(cat project.clj) $(cat $LEIN_HOME/profiles.clj)"
-        INPUT_CHECKSUM=$(echo $INPUTS | shasum - | cut -f 1 -d " ")
-        # Just don't change :target-path in project.clj, mkay?
-        TRAMPOLINE_FILE="target/trampolines/$INPUT_CHECKSUM"
-    else
-        TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
-        trap "rm -f $TRAMPOLINE_FILE" EXIT
-    fi
-
+    TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
     if [ "$OSTYPE" = "cygwin" ]; then
         TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
     fi
 
-    if [ "$INPUT_CHECKSUM" != "" ] && [ -r "$TRAMPOLINE_FILE" ]; then
-        if [ $DEBUG ]; then
-            echo "Fast trampoline with $TRAMPOLINE_FILE."
-        fi
-        exec sh -c "exec $(cat $TRAMPOLINE_FILE)"
+    $LEIN_JAVA_CMD \
+        -client -XX:+TieredCompilation \
+        $LEIN_JVM_OPTS \
+        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
+        -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
+        -cp "$CLASSPATH" \
+        clojure.main -m leiningen.core.main "$@"
+
+    EXIT_CODE=$?
+
+    if [ -r $TRAMPOLINE_FILE ]; then
+        TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
+        rm $TRAMPOLINE_FILE
+        exec sh -c "exec $TRAMPOLINE"
     else
-        export TRAMPOLINE_FILE
-        $LEIN_JAVA_CMD \
-            -client -XX:+TieredCompilation \
-            $LEIN_JVM_OPTS \
-            -Dfile.encoding=UTF-8 \
-            -Dmaven.wagon.http.ssl.easy=false \
-            -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -classpath "$CLASSPATH" \
-            clojure.main -m leiningen.core.main "$@"
-
-        EXIT_CODE=$?
-
-        if [ -r "$TRAMPOLINE_FILE" ]; then
-            TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
-            if [ "$INPUT_CHECKSUM" = "" ]; then
-                rm $TRAMPOLINE_FILE
-            fi
-            exec sh -c "exec $TRAMPOLINE"
-        else
-            exit $EXIT_CODE
-        fi
+        exit $EXIT_CODE
     fi
 fi
