[haus] [lein] Leiningen update

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,7 +1,6 @@
 #!/bin/sh
 
-LEIN_VERSION="1.6.2"
-export LEIN_VERSION
+export LEIN_VERSION="1.7.0-SNAPSHOT"
 
 case $LEIN_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
@@ -35,13 +34,13 @@ done
 if [ "$LEIN_HOME" = "" ]; then
   if [ -d "$PWD/.lein" ] && [ "$PWD" != "$HOME" ]; then
     echo "Leiningen is running in bundled mode."
-    LEIN_HOME="$PWD/.lein"
+    export LEIN_HOME="$PWD/.lein"
   else
-    LEIN_HOME="$HOME/.lein"
+    export LEIN_HOME="$HOME/.lein"
   fi
 fi
 
-DEV_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null)"
+DEV_PLUGINS="$(ls -1 lib/dev/*jar .lein-plugins/*jar 2> /dev/null)"
 USER_PLUGINS="$(ls -1 "$LEIN_HOME"/plugins/*jar 2> /dev/null)"
 
 artifact_name () {
@@ -129,10 +128,24 @@ if type -p curl >/dev/null 2>&1; then
     HTTP_CLIENT="curl $CURL_PROXY --insecure -f -L -o"
 fi
 
+# If we don't have Leiningen's own Clojure on the bootclasspath, boot
+# will be slower, and versions of Clojure in :dev-dependencies can
+# take precedence.
+if [ ! -r "$CLOJURE_JAR" ]; then
+    CLOJURE_JAR_URL=http://build.clojure.org/releases/org/clojure/clojure/1.2.1/clojure-1.2.1.jar
+    CLOJURE_HASH="be088d20c078ce48d42afba05984f1ef7c02142b  clojure-1.2.1.jar"
+    mkdir -p "$(dirname $CLOJURE_JAR)"
+    $HTTP_CLIENT $CLOJURE_JAR $CLOJURE_JAR_URL
+    if [ "`sha1sum $CLOJURE_JAR`" != "$CLOJURE_HASH" ]; then
+        echo "WARNING: Clojure jar failed to download from $CLOJURE_JAR_URL"
+    fi
+fi
+
 export JAVA_CMD=${JAVA_CMD:-"java"}
+export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}
 
 # Support $JAVA_OPTS for backwards-compatibility.
-export JVM_OPTS=${JVM_OPTS:-"$JAVA_OPTS"}
+export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
 
 # TODO: investigate http://skife.org/java/unix/2011/06/20/really_executable_jars.html
 # If you're packaging this for a package manager (.deb, homebrew, etc)
@@ -234,26 +247,25 @@ else
     # doesn't exist everything will still work, it will just have a
     # slower JVM boot.
     test $CYGWIN_JLINE && stty -icanon min 1 -echo
-    if [ "$1" = "trampoline" ]; then
-        TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
-        if [ "$OSTYPE" = "cygwin" ]; then
-            TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
-        fi
-        $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -Dleiningen.trampoline-file=$TRAMPOLINE_FILE -cp "$CLASSPATH" \
-            $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
-        if [ -r $TRAMPOLINE_FILE ]; then
-            TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
-            rm $TRAMPOLINE_FILE
-            exec sh -c "exec $TRAMPOLINE"
-        fi
-    else
-        exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
+    TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
+    if [ "$OSTYPE" = "cygwin" ]; then
+        TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
+    fi
+
+    ## TODO: -XX:+UseCompressedOops only works on 64 bit jvm
+    # is there some way of detecting 64bit at this stage? - tavisrudd
+    $LEIN_JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
+        $LEIN_JVM_OPTS -XX:+TieredCompilation \
+        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
+        -Dleiningen.trampoline-file=$TRAMPOLINE_FILE -cp "$CLASSPATH" \
+        $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
+        $NULL_DEVICE "$@"
+    EXIT_CODE=$?
+    if [ -r $TRAMPOLINE_FILE ]; then
+        TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
+        rm $TRAMPOLINE_FILE
+        exec sh -c "exec $TRAMPOLINE"
     fi
     test $CYGWIN_JLINE && stty icanon echo
+    exit $EXIT_CODE
 fi
