[bash] +comps

diff --git a/etc/bashrc.d/bash_completion b/etc/bashrc.d/bash_completion
--- a/etc/bashrc.d/bash_completion
+++ b/etc/bashrc.d/bash_completion
@@ -771,7 +771,7 @@ __parse_options()
             *)    break ;;
         esac
     done
-    [[ $option ]] || return
+    [[ $option ]] || return 0
 
     IFS=$' \t\n' # affects parsing of the regexps below...
 
@@ -928,8 +928,7 @@ _ip_addresses()
     esac
     local PATH=$PATH:/sbin
     local addrs=$( { LC_ALL=C ifconfig -a || ip addr show; } 2>/dev/null |
-        command sed -ne \
-            's/.*addr:\([^[:space:]]*\).*/\1/p' -ne \
+        command sed -e 's/[[:space:]]addr:/ /' -ne \
             "s|.*inet$n[[:space:]]\{1,\}\([^[:space:]/]*\).*|\1|p" )
     COMPREPLY+=( $( compgen -W "$addrs" -- "$cur" ) )
 }
@@ -1359,6 +1358,7 @@ _get_first_arg()
 # @param $1 chars  Characters out of $COMP_WORDBREAKS which should
 #     NOT be considered word breaks. See __reassemble_comp_words_by_ref.
 # @param $2 glob   Options whose following argument should not be counted
+# @param $3 glob   Options that should be counted as args
 _count_args()
 {
     local i cword words
@@ -1366,8 +1366,9 @@ _count_args()
 
     args=1
     for (( i=1; i < cword; i++ )); do
-        if [[ ${words[i]} != -* && ${words[i-1]} != $2 ]]; then
-           args=$(($args+1))
+        if [[ ${words[i]} != -* && ${words[i-1]} != $2 ||
+              ${words[i]} == $3 ]]; then
+            args=$(($args+1))
         fi
     done
 }
@@ -1899,8 +1900,7 @@ complete -F _longopt a2ps awk base64 bash bc bison cat chroot colordiff cp \
     texindex touch tr uname unexpand uniq units vdir wc who
 
 # declare only knows -g in bash >= 4.2.
-if [[ ${BASH_VERSINFO[0]} -gt 4 ||
-      ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -ge 2 ]]; then
+if [[ ${BASH_VERSINFO[0]} -gt 4 || ${BASH_VERSINFO[1]} -ge 2 ]]; then
     declare -Ag _xspecs
 else
     declare -A _xspecs
@@ -1941,6 +1941,13 @@ _filedir_xspec()
         }
         ))
 
+    # Try without filter if it failed to produce anything and configured to
+    [[ -n ${COMP_FILEDIR_FALLBACK:-} && ${#toks[@]} -lt 1 ]] && {
+        local reset=$(shopt -po noglob); set -o noglob
+        toks+=( $( compgen -f -- "$(quote_readline "$cur")" ) )
+        IFS=' '; $reset; IFS=$'\n'
+    }
+
     if [[ ${#toks[@]} -ne 0 ]]; then
         compopt -o filenames
         COMPREPLY=( "${toks[@]}" )
@@ -1957,7 +1964,7 @@ _install_xspec()
 }
 # bzcmp, bzdiff, bz*grep, bzless, bzmore intentionally not here, see Debian: #455510
 _install_xspec '!*.?(t)bz?(2)' bunzip2 bzcat pbunzip2 pbzcat lbunzip2 lbzcat
-_install_xspec '!*.@(zip|[egjsw]ar|exe|pk3|wsz|zargo|xpi|s[tx][cdiw]|sx[gm]|o[dt][tspgfc]|od[bm]|oxt|epub|apk|ipa|do[ct][xm]|p[op]t[mx]|xl[st][xm]|pyz|whl)' unzip zipinfo
+_install_xspec '!*.@(zip|[egjswx]ar|exe|pk3|wsz|zargo|xpi|s[tx][cdiw]|sx[gm]|o[dt][tspgfc]|od[bm]|oxt|epub|apk|ipa|do[ct][xm]|p[op]t[mx]|xl[st][xm]|pyz|whl)' unzip zipinfo
 _install_xspec '*.Z' compress znew
 # zcmp, zdiff, z*grep, zless, zmore intentionally not here, see Debian: #455510
 _install_xspec '!*.@(Z|[gGd]z|t[ag]z)' gunzip zcat
@@ -1975,7 +1982,7 @@ _install_xspec '!*.@(dvi|DVI)?(.@(gz|Z|bz2))' xdvi kdvi
 _install_xspec '!*.dvi' dvips dviselect dvitype dvipdf advi dvipdfm dvipdfmx
 _install_xspec '!*.[pf]df' acroread gpdf xpdf
 _install_xspec '!*.@(?(e)ps|pdf)' kpdf
-_install_xspec '!*.@(okular|@(?(e|x)ps|?(E|X)PS|[pf]df|[PF]DF|dvi|DVI|cb[rz]|CB[RZ]|djv?(u)|DJV?(U)|dvi|DVI|gif|jp?(e)g|miff|tif?(f)|pn[gm]|p[bgp]m|bmp|xpm|ico|xwd|tga|pcx|GIF|JP?(E)G|MIFF|TIF?(F)|PN[GM]|P[BGP]M|BMP|XPM|ICO|XWD|TGA|PCX|epub|EPUB|odt|ODT|fb?(2)|FB?(2)|mobi|MOBI|g3|G3|chm|CHM)?(.?(gz|GZ|bz2|BZ2)))' okular
+_install_xspec '!*.@(okular|@(?(e|x)ps|?(E|X)PS|[pf]df|[PF]DF|dvi|DVI|cb[rz]|CB[RZ]|djv?(u)|DJV?(U)|dvi|DVI|gif|jp?(e)g|miff|tif?(f)|pn[gm]|p[bgp]m|bmp|xpm|ico|xwd|tga|pcx|GIF|JP?(E)G|MIFF|TIF?(F)|PN[GM]|P[BGP]M|BMP|XPM|ICO|XWD|TGA|PCX|epub|EPUB|odt|ODT|fb?(2)|FB?(2)|mobi|MOBI|g3|G3|chm|CHM)?(.?(gz|GZ|bz2|BZ2|xz|XZ)))' okular
 _install_xspec '!*.pdf' epdfview pdfunite
 _install_xspec '!*.@(cb[rz7t]|djv?(u)|?(e)ps|pdf)' zathura
 _install_xspec '!*.@(?(e)ps|pdf)' ps2pdf ps2pdf12 ps2pdf13 ps2pdf14 ps2pdfwr
